# CloudFormationTemplateVersion
# Description

AWSTemplateFormateVersion: "2010-09-09"
Description: "CloudFormation Template For S3 Bucket"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "Qasim-S3-Bucket-YAML"
